// Add new letters to the TOP of this array (newest first).
// Type: 'essay' (longer, 5+ min read) | 'note' (2-4 min, Saturday note)
// Body: array of paragraph strings. Use ** for **bold**.

export const LETTERS = [
  {
    slug: 'its-an-inside-job',
    title: "It's an inside job. You can't get inside.",
    date: '2026-06-06',
    type: 'essay',
    topic: 'emotional-literacy',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "The number one concern for American parents is their child's mental health. Here's what we actually control.",
    dek: "The number one concern for American parents is their child's mental health. Here's what we actually control.",
    img: null,
    featured: true,
    related: ['when-they-cant-name-it', 'its-cool-to-care'],
    body: [
      "I finally got back on the calendar with my therapist last week. He could tell I was carrying a lot. Visible and verbal weight were on my face and chest.",
      "\"I'm just feeling…lonely.\" As we unpacked it, so much of what was barring my connection was helplessness. I felt unable to help, support or change pain for people around me, and it weighed on me.",
      "There's an incredible loneliness that happens in our life when we can't fix something for someone we love. It's like we're standing at a locked door trying to communicate with them through the door. Barking instructions, resisting the urge to break it down.",
      "There's this urgency and restraint that combine into a pain we can't really describe except through a sigh and clenched jaw.",
      "As parents, we picture ourselves in this analogy on the outside of the door, our kids inside. And many of us feel like we're living that reality, every day. Access to our kids' inner lives feels fleeting, emotional firewalls fly up with phones and shrugs.",
      "We extrapolate. We presume a lack of communication to be a sign of anxiety and depression, disconnection and purposelessness.",
      "The number one concern for American parents is the mental health of their child. Over 50% of American parents have significant fear about the mental health of their kid.",
      "That's because we understand what it means to be on both sides of the door.",
      "Parents, we've been trapped in our heads with anxiety. We've doomscrolled through the depression of world affairs. We've wrestled with futility and purpose. The empathy we have for a child walking into that world creates a distressing urgency inside of us.",
      "\"Get them to safety.\" We think, but we can't guarantee it, completely. Those instincts are generous, but misplaced.",
      "Because having been inside those feelings, we all know that the only way we get to stability is tools, support, and agency. It's a three legged stool.",
      "Instead of dismay, we can parent with more clarity.",
      "We are the first source of tools our children have to understand their inner life. The way we communicate, repair. We teach them how to communicate in conflict, distress, joy, growth, and failure. These are the maps that our kids will take with them.",
      "We are the first source of support. We prioritize connection. We challenge them, and scaffold the inner voice. We teach them what it feels like to be seen, safe and supported.",
      "But we aren't the third leg, and we can't be. We aren't their agency. And the third leg is what's emergent in adolescence, and the only way that they can understand the importance of their own process is if we prioritize it for ourselves.",
      "Try this this weekend: do the thing you've been putting off for your own inner life — book the appointment, take the walk, say the hard true thing out loud — and let your kid see you do it. You're showing them the door opens from the inside.",
    ],
  },
  {
    slug: 'its-cool-to-care',
    title: "Apathy isn't a character flaw. It's armor.",
    date: '2026-05-30',
    type: 'essay',
    topic: 'relationship',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "When your kid shrugs at the thing they used to love, they're not telling you who they are. They're telling you what they're protecting.",
    dek: "When your kid shrugs at the thing they used to love, they're not telling you who they are. They're telling you what they're protecting.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'take-care-of-your-own-backyard'],
    body: [
      "My high school students used to call me a try-hard. \"Mr., you're crazy, dude. Such a try-hard.\"",
      "I'd say, \"Absolutely. 100%. I'm a try-hard.\"",
      "Because what they were actually doing in those moments wasn't insulting me. They were probing. Trying to figure out why I cared. Because the dominant social posture among middle schoolers and teenagers is apathy — and apathy is a social skill, not a character flaw.",
      "Here's what I mean. When a kid says \"I don't care,\" they are usually doing one of three things: they are protecting themselves from looking like they tried and failed. They are protecting their autonomy from adults who have been telling them what's important for as long as they can remember. They are protecting themselves from a world that, honestly, looks pretty overwhelming from the inside of a 12-year-old's phone.",
      "**Apathy is armor.** It's a way of saying \"you can't disappoint me, you can't control me, and I refuse to be naive.\" In a developmental phase defined by hyper-vigilant social scanning — where every move is being watched and graded — caring out loud is genuinely risky. Effort is exposure. And if you've been burned once, the cheapest way to never get burned again is to perform not caring.",
      "So when your kid shrugs at the thing they used to love, or rolls their eyes at the project they secretly worked hard on, or says \"whatever, it's stupid\" about something that clearly mattered an hour ago — they are not telling you who they are. They are telling you what they are protecting.",
      "The job is not to lecture them out of it. You can't argue a kid into caring. The harder you push, the more the armor hardens, because now caring means siding with you against their own social instincts.",
      "The job is to model that effort and enthusiasm is not embarrassing. That it's actually cool to care. That the adults they trust are people who try at the things that matter to them.",
      "This week, let your kid see you care about something. Not perform it, not lecture about it. Just be visibly enthusiastic about something — your work, a hobby, a friendship, a problem you're trying to solve — and let them watch you stay with it when it's hard. No commentary required. You're not trying to convince them caring is good. You're showing them what it looks like.",
    ],
  },
  {
    slug: 'the-slow-kid',
    title: "I've spent years trying to fix the slow kid. I think the slow kid is trying to fix me.",
    date: '2026-05-23',
    type: 'essay',
    topic: 'resilience',
    tag: 'Newsletter · 3 min read',
    readTime: '3 min read',
    excerpt: "Yelling at your kid to hurry up is the thing slowing your morning down. Here's the neuroscience — and a different way in.",
    dek: "Yelling at your kid to hurry up is the thing slowing your morning down. Here's the neuroscience — and a different way in.",
    img: null,
    featured: false,
    related: ['your-kid-already-knows', 'take-care-of-your-own-backyard'],
    body: [
      "I've spent years trying to fix the slow kid. I'm starting to think the slow kid is trying to fix me.",
      "One of my sons wakes up later than everyone, quietly wanders into the shower, takes too long. Last to be dressed, last to get breakfast, last in the car. Some mornings I've handled it well. Some mornings I haven't. I've tried timers, scaffolds, every strategy in the comments section. We're all stuck in the same loop.",
      "The other day I was working hard not to lose it. The win in those moments, for me, isn't being on-time. The win is not creating more harm. And while I was standing in the kitchen, quietly boiling, I had a thought I haven't been able to put down.",
      "What if he's right to be this slow? What if I'm the crazy one for being so beholden to the clock?",
      "Part of his pace is just who he is — attention span, personality, fatigue, all of it mixed in. But part of it, I think, is his nervous system trying to teach me: this pace is not good for us.",
      "Chronic urgency isn't neutral. It's a low-grade stress dose, repeated daily, and the research on it is unambiguous. Sustained activation of the stress system — cortisol elevated for hours, every morning and evening — is associated with sleep disruption, attention dysregulation, anxiety, and long-term cardiometabolic risk. Adults know this. We've named it: burnout. We treat it as a crisis when it shows up at work. We rarely name its infancy when it shows up in our kitchens.",
      "My slow kid isn't broken. He hasn't yet learned to override his body. He hasn't built the calluses yet that let an adult run on cortisol from 6 AM to 9 PM and call it normal. His resistance to the fire drill isn't immature or irresponsible. **It's a productive adaptation to a culture that is, in measurable ways, killing the adults inside it.**",
      "And before you say, \"But I don't have time…\", remember: escalating into urgency makes everything worse. When I yell at the slow one, his amygdala kicks on and his prefrontal cortex — the part responsible for sequencing, planning, and finishing the next task — goes offline. That's not a metaphor. It's the brain prioritizing survival over execution. Yelling about the shoes does not produce the shoes. It produces a fight, a flurry, a frozen kid, and a slower morning. The intensity I was using to get him moving is the exact thing keeping him stuck.",
      "So I'm not arguing with the schedule. School starts when it starts. The schedule isn't the variable — our intensity is. A morning can run on time without running on emergency. The fire drill isn't built into the clock; it's built into us. And our kids are watching us model what an acceptable adult life feels like in the body. When every morning starts in cortisol, we're teaching them that adulthood is something you survive at high speed.",
      "I'd like to teach them something else.",
      "Try this tomorrow morning: when the slow one is being slow, before you reach for the clock, slow down yourself. Drop your shoulders. Lower your voice. And ask one normal question — *Hey bud, where are you at?* You're doing two things at once. You're calming your own cortisol so you can actually think. And you're telling your kid that he matters more than the calendar.",
      "Sometimes the slowest body in the room is the wisest one. Not because time isn't real. Because we're not the standard he should be calibrating to.",
    ],
  },
  {
    slug: 'your-kid-already-knows',
    title: "Your kid already knows.",
    date: '2026-05-16',
    type: 'essay',
    topic: 'communication',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "Every time you try to prove you're right or drive the point home, you're robbing them of the chance to draw that conclusion themselves.",
    dek: "Every time you try to prove you're right or drive the point home, you're robbing them of the chance to draw that conclusion themselves.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'when-they-cant-name-it'],
    body: [
      "Every time you try to fix the situation. Every time you try to prove you're right. Every time you make sure they understand the seriousness of what they did — you're robbing them of the chance to draw those conclusions on their own.",
      "Here's what I know about the parents reading this. You've installed the structure. You've modeled the values. You've had the conversations a hundred times. Your kid can tell the difference between right and wrong. They know when they've crossed a line. They know when they're disconnected from you. The intuition is in there.",
      "We all have this. I know I should go to the gym. I know I shouldn't eat the cookie. I know I should call my brother. We all carry a quiet inner voice that tells us the right thing to do.",
      "But think about how it lands when your spouse turns to you and says, \"You don't need to be eating that cookie.\"",
      "Don't tell me what to do. I know. Of course I don't need to be eating this cookie. I'm bored, today kind of sucked, and I'm eating it anyway.",
      "Now your intuition isn't speaking to you. It's reacting to them. It's not giving you clarity or guidance — it's just defending itself.",
      "**That's what's happening when we react fast and talk too much with our kids.** Their intuition was about to kick in. They were about to think \"I need to sit with this for a second.\" And then we filled the space. We delivered the lesson, named the consequence, made sure they understood the seriousness.",
      "And now their developing inner voice — the one we've been trying to build for thirteen years — gets shoved aside so they can react to us instead.",
      "This is the developmental piece a lot of parents miss. That intuition we have, that on-demand reflective process? Our middle schoolers don't have it yet. Not the way we do. It takes them a beat. Sometimes a long beat. They have to feel the weight of the moment, register the disconnection, and let their own values catch up.",
      "**That beat is the entire skill.**",
      "When we react fast, we don't just miss the moment — we replace it. Their internal process becomes external conflict with us. And the next time something goes wrong, their intuition is even quieter, because it's been trained to wait for our voice instead of its own.",
      "I'm not saying don't have boundaries. Boundaries are right. Hold the line. But once the line is held, get out of the way.",
      "This week, try this: when your kid does the thing — the rude tone, the missed chore, the dumb decision — say less than you want to. Hold the boundary, name it once, and then stop. Give them sixty seconds of nothing. No follow-up. No clarification. No making sure they got it.",
      "They got it. Let their intuition do the work it was built to do.",
    ],
  },
  {
    slug: 'take-care-of-your-own-backyard',
    title: "Take care of your own backyard.",
    date: '2026-05-09',
    type: 'essay',
    topic: 'reflection',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "It took me 20 years, hundreds of students, and 3 kids to understand what my mother meant.",
    dek: "It took me 20 years, hundreds of students, and 3 kids to understand what my mother meant.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'its-cool-to-care'],
    body: [
      "As an impassioned 22-year-old volunteer teacher I was ready to fix the world in a year.",
      "My mother slowed me down with six words from her grandfather — a career restaurateur and barman who greeted the world with a smile and conversation — \"Take care of your own backyard.\"",
      "It took me 20 years, hundreds of students, and 3 kids to realize what she meant.",
      "My mother was a child development major — a major she invented with the dean inside Boston College's Carroll School of Education because she wasn't going to be a teacher or social worker, and her course selection evaded classification. She worked with adults with disabilities before moving 3 times with 3 young kids took over our lives. She knew the psychology and development frames, and had the training that made me later ask her \"Why don't you run a school?\" She didn't need scripts, routines, and frameworks because she had something better: she had agency and intent.",
      "In a single look your direction, she was resilient, patient, gentle and demanding. Her love was the grace and space that allowed us to feel safe in our mess, and a quiet confidence that we would do the right thing for others and in so doing find ourselves.",
      "**What she meant, when she reminded me to \"take care of my own backyard,\" was that the single most important thing I controlled was the way I showed up every day** — because the measure of a life is in human relationship.",
      "We give them our full attention. We are grateful for all parts of them. We don't worry about the return or the outcome because the giving is the living.",
      "She never said any of this to me. She just taught it to me when she sat in the dark with me and listened. You can do that too — it's simpler than you realize.",
      "So try this this week: give yourself permission to leave your phone in the other room, sit at the dinner table with your kids for way too long. Or sit on their bed in the dark well past lights out, and listen. And when you see them next, just be glad they are there.",
    ],
  },
  {
    slug: 'when-they-cant-name-it',
    title: "When they can't name it, they blame it.",
    date: '2026-05-02',
    type: 'essay',
    topic: 'emotional-literacy',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "There are 3,000 words for feelings in English. Our kids have access to maybe twelve. Here's what happens when the vocabulary runs out.",
    dek: "There are 3,000 words for feelings in English. Our kids have access to maybe twelve. Here's what happens when the vocabulary runs out.",
    img: null,
    featured: false,
    related: ['its-an-inside-job', 'your-kid-already-knows'],
    body: [
      "When emotional vocabulary is thin, the nearest person becomes the cause of discomfort.",
      "A hangry kid will look you dead in the eye when you ask them to set the table and say, \"YOU DON'T THINK I CAN DO ANYTHING RIGHT?!\" Then, twenty minutes after dinner, you ask them to help with the dishes and they say, \"Of course.\"",
      "We laugh at that one because it's familiar. But the same misfire happens in subtler, more damaging ways every week. A kid is frustrated by a new assignment and blows up on their brother for walking in the room. A kid feels embarrassed when they miss an instruction in class and decides the teacher hates them. A kid is exhausted by your perfectly reasonable feedback and decides you're trying to ruin their life. And you're left holding the bag, wondering what just happened.",
      "Here's what's actually happening: **when a kid can't name what they're feeling, they default to blame.** Whoever made the demand becomes the source of the dysregulation. You asked for the table to get set, so you must be the problem. The teacher gave the instruction, so the teacher must hate them. The brother walked in the room, so the brother must be annoying.",
      "Blame is the dead giveaway of a missing skill.",
      "When emotional intelligence is online, a kid can pause and recognize, *I'm uncomfortable, and that discomfort is mine to manage.* When it isn't, the discomfort has to come from somewhere — so they look around and assign it to the nearest available person. Usually you.",
      "This isn't manipulation. It isn't disrespect. It's a kid grabbing the closest available label for a feeling they don't have words for, and then building a story on top of that label like it's the truth. There are 3,000 words for feelings in English, and our kids have access to maybe twelve. So *mad* and *unfair* and *you* do a lot of heavy lifting they shouldn't have to do.",
      "If you can hear the blame as a signal — not as an accusation — the whole interaction changes. You stop defending yourself and start scaffolding the skill they're missing.",
      "You can't tell a kid \"you're feeling the wrong thing\" in the moment. That's a fight you'll lose. But you can come back to it later.",
      "Try this: tonight or this week, after the storm passes, go back to a recent blowup and ask, \"What do you think you were actually feeling right then? Because you caused some harm thinking everyone was out to get you.\" Then sit in the silence — don't rescue them. Let them try a word. If it's wrong, offer two more: \"Could it have been embarrassed? Frustrated? Tired?\" You're not interrogating. You're offering vocabulary in multiple choice.",
      "That replay and reflection is where the skill gets built. One quiet conversation at a time. The kid who learns to catch their own blame reflex becomes a better partner, a better sibling, a better friend, and eventually a much better adult.",
      "It's a skill. It can be learned, and our kids will be better people for it.",
    ],
  },
  {
    slug: 'autonomy-grows-in-the-space',
    title: "Autonomy grows in the space we don't occupy.",
    date: '2026-04-25',
    type: 'essay',
    topic: 'autonomy',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "My son is batting .090 and loves baseball more than any sport in the world. The reason is his coach — and what his coach doesn't do.",
    dek: "My son is batting .090 and loves baseball more than any sport in the world. The reason is his coach — and what his coach doesn't do.",
    img: null,
    featured: false,
    related: ['your-kid-already-knows', 'its-cool-to-care'],
    body: [
      "My son is batting about .090 this season. And he loves baseball more than any sport in the world right now.",
      "He's been working at it. Watching YouTube. Hitting balls in the yard. Swinging his bat full speed in the kitchen while I'm trying to cook.",
      "This weekend, he hit his first real double, and doubled down on the work after.",
      "The only reason he's still in it is his coach. A guy who has stayed patient, curious, stayed collaborative, and has always found a way for my son to contribute to the team outside of the batter's box.",
      "My job? Resisting every coaching instinct I have. Staying curious. Giving him the autonomy to chase the thing he is naturally motivated to chase — hitting baseballs.",
      "And here's what I keep coming back to: in middle school, what our kids want more than almost anything is to understand their own agency. Their own power. To feel like the things they care about are theirs, not assigned. **And that feeling will never come from our instructions. It can only come from the space we leave for it.**",
      "Research on adolescent motivation backs this up — kids this age are wired to protect autonomy and resist feeling controlled, even when the \"control\" is well-meaning coaching from the people who love them most. The more we steer, the more we communicate that the thing isn't really theirs.",
      "Our influence is real, but it's quieter than we think. We don't author who our kids become. What we do shape is the environment around them. The spaces they move through. The people they're around when we're not there. The conditions that let them find the version of themselves they actually like being.",
      "I notice it with my oldest. When the inputs are right — the right friends, enough sleep, real things to care about — the kid is a joy. Not because I'm enjoying him. Because he is enjoying him. And I get to watch that.",
      "We all have a version of ourselves we're our best in. For me it's family and old friends and food on a table. For my wife, it's something else entirely, and I love watching her find it. Our kids deserve the same — a chance to find the rooms, the people, the activities where their best self shows up without being summoned.",
      "Our job isn't to define that for them. It's to leave room for it. To encourage the pursuit. To resist the instinct to coach the swing when what they actually need is the space to keep learning.",
      "This week, try this: the next time your kid finishes a practice, a game, a hard test, a rough social moment — don't lead with feedback. Don't lead with questions either. Try \"Good to see you,\" and let the silence sit.",
      "And when you do talk about the thing they're working on, swap the coaching sentence for a curious one. Instead of \"You should…\" or \"Next time, try…\", try: \"What are you working on?\" \"What do you want to try next?\" \"What's the hard part?\" Same situation. Different approach. Because the thing most middle schoolers rarely feel from their parents is this: **that being around you isn't an evaluation, and autonomy grows in the space we don't occupy.**",
    ],
  },
];
