// Add new letters to the TOP of this array (newest first).
// Type: 'essay' (longer, 5+ min read) | 'note' (2-4 min, Saturday note)
// Body: array of paragraph strings. Use ** for **bold**.

export const LETTERS = [
  {
    slug: 'dont-change-the-song',
    title: "Stop letting your kid change the song in the car",
    date: '2026-07-24',
    type: 'essay',
    topic: 'adaptation',
    tag: 'Newsletter · 5 min read',
    readTime: '5 min read',
    excerpt: "A small parenting pet peeve that's actually a discomfort-tolerance lesson hiding in plain sight.",
    dek: "A small parenting pet peeve that's actually a discomfort-tolerance lesson hiding in plain sight.",
    img: null,
    featured: false,
    related: ['the-slow-kid', 'its-cool-to-care'],
    body: [
      "I have a new rule in the car.",
      "You don't get to change the song.",
      "It's a pet peeve, I'll admit it. My kids get in the car, throw on one of their myriad terrible playlists — there are multiples — and then proceed to spend the entire drive skipping every other song. The algorithm thinks I have horrendous taste in music, which apparently I do, because I allow all of this music to be played in my car.",
      "Skip. Skip. Next. Skip.",
      "It started as just an annoyance. Then I started watching what was actually happening — and I think there's something here.",
      "Here's the thing about constantly skipping the song.",
      "It's not really about the song. It's about a kid practicing the move of get rid of anything that isn't immediately known, immediately comfortable, and immediately likeable. Three seconds in. Verdict rendered. Next.",
      "That's a posture. And once it's a posture in the car, it's a posture everywhere else.",
      "It's the same instinct that makes them only want to hang out with the kids they already know. The same instinct that makes them push the vegetables to the side of the plate without trying them. The same instinct that makes them refuse the new sport, the new book, the new class, the new whatever — before any of it has had time to become anything.",
      "The world is full of things that aren't immediately good. Most of the durable, interesting, worth-it things in a life — friendships, foods, books, skills, jobs, places — require the first thirty seconds of I don't know about this yet before they get good. If a kid has trained their nervous system to bail at second three, they're going to bail on most of what could be theirs.",
      "So we made a rule.",
      "The radio rule: When the playlist comes on, we treat it like the radio. Nobody changes the song.",
      "The only override is a group vote: \"hey, this one's actually not great, can we skip?\" — and yes, that vote tends to go heavily in my favor when I'm the one calling it. Dad privilege. The kids know.",
      "The rule has done two things I didn't expect.",
      "The first: they're listening differently. When you know you can't skip, you actually have to pay attention. They've started noticing songs they would have skipped at second three. \"Oh wait, this one's kind of good.\" Sometimes they're right. Sometimes they're wrong and we sit through forty more seconds of something terrible. Either way, they're practicing the muscle of letting it play out.",
      "The second: they're getting better at making a real case. \"Dad, I really don't like this one, can we skip it?\" — said like a human being asking for something, not a thumb-mashing reflex. That's a different conversation. That's a kid who has noticed a feeling, named it, and decided to ask. Which is the whole emotional intelligence skill, dressed up as a car ride.",
      "This is the bigger thing under it.",
      "In a phone-and-algorithm world, our kids are getting trained at a previously impossible scale to skip anything that doesn't immediately land. Swipe. Next video. Next reel. Next song. Three-second judgments, all day, every day. The reward circuitry gets so used to instant payoff that any delay between I don't know what this is yet and oh, this is good starts to feel intolerable.",
      "That's not a music problem. It's a discomfort-tolerance problem.",
      "And discomfort tolerance is one of those skills that doesn't get built in a sit-down conversation. It gets built in fifty small, low-stakes moments where the kid had the option to bail and didn't. The song they didn't skip. The dinner they tried before pushing it away. The book they read past the first chapter even though it felt slow. The kid at school who seemed boring on Tuesday and turned out to be funny on Thursday.",
      "Every one of those is the same skill: stay with the unknown long enough for it to become something.",
      "The car is just the cheapest, most repeatable rep of that skill available to most families. Five days a week. Captive audience. Built-in three-minute exposure. You're already there.",
      "You might as well use it.",
      "This week, do one thing.",
      "Pick a daily moment where your kid has been bailing fast — the song, the dinner, the homework start, the conversation, the chore. One moment.",
      "And institute a small don't skip rule.",
      "Not forever. Not for everything. Just for this one moment, this one week. You can object after the verse plays. You can decide after three bites. You can tell me you hate it after you've actually read a page.",
      "What you're building isn't the love of the thing they didn't want to do. You're building the part of them that can wait long enough to know what something actually is.",
      "Which, it turns out, is most of what makes a life good.",
    ],
  },
  {
    slug: 'your-kid-cant-tell-time',
    title: "Your kid can't tell time the way you do",
    date: '2026-07-17',
    type: 'essay',
    topic: 'autonomy',
    tag: 'Newsletter · 7 min read',
    readTime: '7 min read',
    excerpt: "Your 12-year-old has taken a thousand showers. He still doesn't know how long one takes. That's not defiance — it's a missing skill, and the skill has a name.",
    dek: "Your 12-year-old has taken a thousand showers. He still doesn't know how long one takes. That's not defiance — it's a missing skill, and the skill has a name.",
    img: null,
    featured: false,
    related: ['the-slow-kid', 'stop-reminding-start-collaborating'],
    body: [
      "I told my kid he had 15 minutes to go take a shower because we were getting ready for bed.",
      "Fifteen minutes later I walked back to check on him, and the shower was not even on.",
      "I nearly lost my mind.",
      "Fifteen minutes. One shower. One human. The most reasonable request in the history of parenting. And he hadn't started. The towel wasn't out. The water wasn't running. He was somewhere in the orbit of the bathroom, doing something that was not the thing.",
      "I stood there with my hand on the doorframe and felt the familiar heat rising up my neck.",
      "Then I made myself stop. Because I know this one. I've taught this one. I know what's actually happening, and it isn't disrespect.",
      "Here's what's going on inside a developing brain.",
      "Time perception is an executive function skill. It's not intuition. It's not common sense. It's a discrete cognitive capacity that gets built slowly through adolescence — the ability to estimate how long a task takes, hold a deadline in working memory while you do something else, and adjust your behavior in real time to land near the target.",
      "Adults take this for granted because we've been running it for decades. You feel ten minutes pass without checking. You know how long it takes to make coffee. You know that we leave in twenty means start moving in fifteen. That internal clock is so reliable that we've stopped noticing it's a skill at all.",
      "Your 12-year-old does not have that clock yet.",
      "He has a wristwatch in the literal sense — maybe. He does not have a wristwatch in the brain sense. The thing inside an adult that quietly says that took longer than I planned, I should speed up hasn't been installed in him. Not yet.",
      "Which means when I said fifteen minutes, what he heard was go shower at some point. The word fifteen did not carry urgency. It carried no weight at all. He walked into the bathroom, got distracted by a mirror, couldn't find a towel, picked something up off the floor that wasn't a towel, looked at it for a while, and lost the thread entirely.",
      "He's taken a million showers. Every single one of them happened without him tracking how long it took. The reps weren't building the skill, because the skill was never the point of the reps. The shower was.",
      "Here's the part I had to remind myself of, standing in the hallway.",
      "His inability to manage time is a source of stress for me. It is not, currently, a source of stress for him. And one of the quiet failure modes of parenting a middle schooler is transferring our stress onto them in moments where they're actually doing fine — and calling that teaching.",
      "The clock is mine. The bedtime is mine. The math of if you don't get in the shower now you won't get enough sleep and tomorrow morning will be ugly is mine.",
      "He's not carrying any of that. Not because he's lazy. Because he literally doesn't have the apparatus to carry it yet.",
      "If I dump that whole load on him in the form of a meltdown about the shower, all I've done is teach him that adults are unpredictable and that the bathroom is a place where dad gets weird. I haven't taught him anything about time.",
      "So I didn't lose it.",
      "I knocked on the doorframe and walked in. Quiet voice. Soft face.",
      "\"Hey, dude. Listen — I sent you in here to shower fifteen minutes ago. I wanted you to knock that out. What's going on?\"",
      "\"Oh… I, uh… yeah. I just kind of lost track of time.\"",
      "\"I can tell. I get it.\"",
      "Long pause. No lecture. No do you understand how late it's getting. Just the silence of two people in a bathroom acknowledging the truth.",
      "\"Five-minute shower. Can you do that?\"",
      "\"Yeah.\"",
      "\"Okay. I'm coming right back.\"",
      "And sure enough — five minutes later, kid pops out, clean, towel on, back on schedule. We're good. Nobody's amygdala kicked on. Nobody had to repair anything.",
      "But more importantly: he just got a calibration rep. Fifteen minutes is longer than I thought. Five minutes is shorter than I thought. Dad walked away and came back, and the time felt different than I expected. That's the data the skill is built from. Not from a lecture about respecting people's time. From a small, low-stakes loop where he got to feel the gap between his estimate and the actual clock.",
      "That's the rep.",
      "Here's what I keep coming back to.",
      "Time management is a skill. It's not intuitive. It's not natural. It's not something they should just get by the time they're twelve. We have to stop using \"why don't you get this?\" as a question and start using it as a diagnostic.",
      "The answer is: they don't. They just don't. Not the way you do. Not yet.",
      "Which means our job isn't to be outraged at the gap. It's to be the calm voice that closes it, one shower at a time.",
      "This week, do one thing.",
      "The next time you give your kid a deadline — fifteen minutes till we leave, twenty till bedtime, ten till dinner — and they blow past it, don't open with frustration.",
      "Open with the question I asked in the bathroom: Hey, what's going on in here?",
      "Then listen for the answer. I lost track. I got distracted. I didn't realize. That answer is not an excuse. It is diagnostic information. It is telling you exactly where the skill is.",
      "Then give them a smaller, more concrete number. Five more minutes. Three more. Something the developing internal clock can actually hold onto.",
      "And come back when you said you would.",
      "Each one of those loops is a rep. The reps are the skill. There is no shortcut.",
    ],
  },
  {
    slug: 'accountability-follows-coping',
    title: "Why your 12-year-old can't take responsibility yet",
    date: '2026-07-03',
    type: 'essay',
    topic: 'emotional-literacy',
    tag: 'Newsletter · 9 min read',
    readTime: '9 min read',
    excerpt: "If your 12-year-old can't take responsibility for the backpack on the floor, you don't have a discipline problem. You have an emotional intelligence gap — and it's the variable underneath everything else.",
    dek: "If your 12-year-old can't take responsibility for the backpack on the floor, you don't have a discipline problem. You have an emotional intelligence gap — and it's the variable underneath everything else.",
    img: null,
    featured: false,
    related: ['when-they-cant-name-it', 'stop-reminding-start-collaborating'],
    body: [
      "If you're standing in your kitchen wondering whether your 12-year-old has developed an early-onset case of mild sociopathy, I have good news and bad news.",
      "The good news: they're not a sociopath.",
      "The bad news: you can't get to accountability with them yet, because accountability is downstream of coping, and coping is downstream of emotional intelligence — and that's still being built.",
      "So we have to start there.",
      "Here's the scene I'm thinking of.",
      "You ask your 12-year-old to pick up their backpack. For the third time. Your tone is mildly frustrated, because — let's be honest — you specifically built the effing mudroom so the shoes and coats and backpacks would stop ending up on the kitchen floor.",
      "And your kid blows a gasket.",
      "\"OH MY GOD I LITERALLY HEARD YOU, BRO. YOU'RE SO ANNOYING.\"",
      "You stand there for a beat. You did not yell. You barely raised your voice. You asked them to do a thing they were already supposed to do, and the response is being treated like a war crime.",
      "It feels disrespectful. It feels disproportionate. It feels, frankly, a little crazy.",
      "It's also exactly what an underdeveloped nervous system does in that moment.",
      "Here's what just happened in their brain.",
      "They felt your tone before they processed your words. Tone does way more work than words when it comes to dysregulating a kid — it goes in faster, it hits harder, and it lands in the part of the brain that asks one question: am I safe right now?",
      "The answer their brain came up with was no.",
      "Not because they were actually in danger. Because they don't yet have the apparatus to interpret a frustrated parent as anything other than threat. The discomfort of your irritation got read as a threat to the relationship, and the fastest way to discharge that discomfort was to fire it back at you. They didn't pick a fight. The fight picked them.",
      "What we want them to be able to do, in that moment, is something like this:",
      "I'm uncomfortable because Dad is irritated. He's irritated because I haven't picked up the backpack three times now. I'm safe. He still loves me. I just need to hang up the backpack.",
      "That sentence — that calm, multi-step act of self-regulation — is what coping looks like.",
      "And in order to say it (even silently), the kid has to do four things in sequence. Notice what they're feeling. Pause long enough to give it space. Find the vocabulary to name it. Use the intellectual capacity to figure out where it's coming from.",
      "That's a lot.",
      "Adults do this on a good day. Often we don't. We snap at our spouse over a dish in the sink and have to circle back twenty minutes later to admit it wasn't actually about the dish.",
      "If we can't always do it at 40, asking a 12-year-old to do it spontaneously, in real time, in a moment of perceived threat, is asking a lot.",
      "Here's the chain that matters.",
      "Emotional intelligence makes coping possible. Coping makes accountability possible. Accountability is what builds empathy and connection — because the moment a kid can acknowledge their behavior affected someone else and take responsibility for it, they are doing the actual work of relationship.",
      "But there is no skipping levels. You cannot get a kid to take responsibility for the backpack if they cannot cope with the discomfort of being asked about the backpack.",
      "That's the whole reframe. If your kid keeps melting down in moments that \"shouldn't\" be a big deal, you don't have a respect problem. You have an emotional intelligence problem — and emotional intelligence is a skill, not a personality trait. It's built through reps.",
      "The reps don't happen in the meltdown. They happen on either side of it.",
      "So while we're standing there in the mudroom, looking at a backpack that has finally — finally — made it onto the hook, here's the move.",
      "Don't let the moment pass with a grunt. Don't let it pass at all.",
      "Name what just happened. Out loud. In your voice.",
      "\"Listen, I know it seems like a small thing, but I want to say thank you for hanging that up. I get frustrated when it ends up on the ground, and I don't like being short with you. So I appreciate you hearing me out and putting it on the hook.\"",
      "Look at what that sentence is doing.",
      "You named your own feeling — I get frustrated. You took ownership of your tone — I don't like being short with you. You modeled empathy — I appreciate you hearing me out. And you gave them specific positive feedback for the behavior you wanted — putting it on the hook.",
      "You just performed, in about fifteen seconds, every component of the emotional intelligence skill you want them to develop. They got to watch it executed in their direction. They got to be the recipient of the empathy you want them to one day extend to other people.",
      "That is the rep.",
      "Not the lecture. Not the consequence. Not the \"thank you\" tossed over your shoulder while you walk away.",
      "The model.",
      "Here's the part that's hard to sit with.",
      "The reason this works is that you went first.",
      "You named your own frustration before you asked them to manage theirs. You took ownership of your tone before you held them accountable for theirs. You modeled empathy before you required it.",
      "This is the order it has to happen in. There is no version of this skill that gets built by a parent demanding it from a child without showing them what it looks like. The kid's emotional intelligence is going to look like yours. The vocabulary they use to name their feelings is going to be the vocabulary they heard you use. The way they handle being dysregulated is going to be the way they watched you handle it.",
      "Which means you are the variable here too.",
      "This week, do one thing.",
      "The next time your kid does the smallest right thing after a hard moment — picks up the bag, comes back to the table, says sorry without being asked — don't let it slip past.",
      "Stop what you're doing. Look at them.",
      "Name your feeling. Take ownership of your tone. Thank them for the specific thing.",
      "Fifteen seconds.",
      "You'll feel a little exposed doing it. That's the point. The exposure is the model. They're learning that adults have feelings too, that adults have language for them, and that adults use that language out loud with the people they love.",
      "That's the skill. That's how it gets passed down.",
    ],
  },
  {
    slug: 'lying-to-stay-close',
    title: "They're not lying to disrespect you. They're lying to stay close to you.",
    date: '2026-06-26',
    type: 'essay',
    topic: 'relationship',
    tag: 'Newsletter · 8 min read',
    readTime: '8 min read',
    excerpt: "When your kid lies about the candy wrapper in their hand, they aren't testing you. They're protecting themselves from you. The fix is quieter than you think.",
    dek: "When your kid lies about the candy wrapper in their hand, they aren't testing you. They're protecting themselves from you. The fix is quieter than you think.",
    img: null,
    featured: false,
    related: ['catch-the-turnaround', 'your-kid-already-knows'],
    body: [
      "Middle school kids will literally deny anything.",
      "They are defensive to a fault, and they will try to tell you that what you just saw wasn't reality.",
      "\"Are you eating candy?\" \"No.\"",
      "\"Put my phone down, please.\" \"I'm not on it.\"",
      "\"You didn't put the shoes away.\" \"I DID.\"",
      "You feel like you're taking crazy pills. You know what you saw. The wrapper is in their hand. The phone is still warm. The shoes are sitting in the hallway exactly where they left them.",
      "And it feels disrespectful, because they're basically lying to your face.",
      "So you push back. \"I literally just watched you.\" And before either of you means to, you're in a power struggle that's not actually about candy or phones or shoes anymore. It's about who's going to win.",
      "Neither of you is going to win.",
      "Here's what's actually happening.",
      "Your kid's impulse control failed. Reward-seeking took over. They knew the choice put them on the wrong side of connection with you, and the second you walked in, their nervous system registered threat.",
      "Not threat to their safety. Threat to their connection with you. Which, at this developmental stage, feels like the same thing.",
      "Middle schoolers are wired for hyper-vigilant social scanning. Status, belonging, and attachment all feel load-bearing. So when they get caught — when they're suddenly aware they're about to be on the outside of your approval — the brain doesn't reach for accountability. It reaches for the fastest tool available to stay inside the relationship.",
      "That tool, for a 12-year-old with underdeveloped impulse control and a fully developed survival instinct, is denial.",
      "They're not lying to disrespect you. They're lying to stay close to you.",
      "It's not strategy. It's not character. It's not them telling you what they think of you. It's a kid grabbing the closest available exit from a moment that feels unsafe.",
      "And here's the part that's hard to swallow: the more aggressive your reaction, the more you confirm what they were already afraid of. You aren't safe to fail in front of. Which means the next time they mess up, they'll lie harder, earlier, and with more conviction.",
      "The intensity you're using to get them to admit it is the exact thing teaching them not to.",
      "The adjustment is simple. It is not easy.",
      "Say nothing. Stand still.",
      "That's it. That's the move.",
      "The silence does two things at once. It creates space for cognitive processing — the half-second their prefrontal cortex needs to catch up to their amygdala and remember that lying to you isn't actually going to work. And it creates neutral emotional pressure, which is different from the loud kind. Neutral pressure is the room not absorbing the denial. It's you, not playing the role they need you to play in order for the deflection to feel justified.",
      "You're not punishing. You're not interrogating. You're just not moving.",
      "Most of the time, this is what happens next: the kid corrects themselves. They stop. They look at the wrapper. They take a small breath. They say something like \"…okay, yeah, I had one.\" Or they put the phone down. Or they go pick up the shoes.",
      "When that happens, you acknowledge it. \"Thanks for telling me.\" Or just a nod. Then you have the conversation about the boundary if there is one to have. Calmly. Briefly. Done.",
      "You just taught them something that no lecture would have taught them: that the room can hold the truth. That admitting it doesn't cost them you.",
      "What we're actually coaching here is the safety to fail.",
      "And the safety to fail starts with the stupid stuff. The candy wrapper. The phone they weren't supposed to be on. The shoes in the hallway.",
      "It looks small because it is small. That's the point. We are running reps on something they're going to need later, when the stakes climb.",
      "Because the stakes are going to climb.",
      "The night they sneak out. The midterm they bombed and hid. The party they're stuck at and shouldn't have gone to. The friend who's struggling and asked them not to tell. The mistake they made online that they don't know how to take back.",
      "Every one of those moments is going to come with the same nervous system question their brain is asking right now about the candy wrapper: Is it safer to tell them, or safer to lie?",
      "The answer to that question is being written right now, in the way you respond to the small stuff. Not in the speech you plan to give them when they're 16. In your face, tonight, when they say \"I didn't\" and you know they did.",
      "Some parents will read this and call it soft. You're just letting them lie.",
      "I'd argue the opposite. A kid who can anticipate that you'll stay regulated when they fail — combined with the awareness that they're permitted to fail in front of you — develops more mature cognitive processing, not less. They start telling the truth earlier because the truth has stopped costing them the relationship. They start catching their own impulses because they don't have to spend the energy on the cover-up.",
      "Accountability doesn't have to be loud and dramatic. It can be silent and small.",
      "The version of your kid that calls you at 1 AM from the party they shouldn't be at is built right now, with the candy wrapper in their hand.",
      "Tonight, do one thing.",
      "The next time you catch your kid in a small denial — the wrapper, the phone, the shoes, the homework — don't push back. Don't ask the follow-up question. Don't say \"are you sure?\"",
      "Just stop. Stand still. Let the room hold what just happened.",
      "Count to ten in your head if you need to.",
      "Then watch what happens in your kid's face.",
      "That tiny, almost-invisible recalibration — the small breath, the dropped shoulders, the \"…okay, yeah\" — is the muscle of honesty firing for maybe the first time without you forcing it.",
      "That's the rep. That's the one you came for.",
    ],
  },
  {
    slug: 'catch-the-turnaround',
    title: "Catch the turnaround",
    date: '2026-06-19',
    type: 'essay',
    topic: 'relationship',
    tag: 'Newsletter · 8 min read',
    readTime: '8 min read',
    excerpt: "After your next fight, your kid will give you a four-second window. What you do with it is what they'll remember about love.",
    dek: "After your next fight, your kid will give you a four-second window. What you do with it is what they'll remember about love.",
    img: null,
    featured: false,
    related: ['its-an-inside-job', 'lying-to-stay-close'],
    body: [
      "After your next fight, your kid is going to do something that no one teaches you to notice — but I know you've felt it. It will last about four seconds.",
      "When things get hard, your kid is going to turn back to you. They'll walk back into the living room after they stormed out, sighing, and quietly say something half-funny. The half-hug. The question about what you're watching. The way they wander into your bedroom and just stand there.",
      "That moment is everything.",
      "This is the turnaround. The moment when something deep in your kid says I want back in, and they take the risk of asking without knowing how. They don't know how to apologize yet. They don't have the words. They just know that being away from you feels worse than whatever the fight was about.",
      "It's that same toddler reaching their hands up in the air to be picked up and held.",
      "Same instinct. Different body. Different vocabulary. Same wordless ask.",
      "Middle schoolers are at a strange developmental hinge. They have an adult-sized need for repair and a kid-sized toolkit for asking for it. The emotional impulse is fully online — I miss you, I'm scared, I need to come back — but the language to carry it doesn't catch up for another decade.",
      "So they improvise. The half-funny comment. The casual question about your show. The reappearance in your doorway with nothing in particular to say.",
      "That is the apology. The first one they know how to make. If we're waiting for the verbal version — \"I'm sorry, you were right\" — we're going to miss every one of them.",
      "Daniel Siegel has written about this for years: secure attachment isn't built on the absence of rupture. It's built on what happens after. Every conflict you have with your kid is a chance to teach them that the relationship is bigger than the worst moment in it. The four-second window is where that lesson actually lands. Not the lecture you'll give later. The smile they get when they walk back in.",
      "If you catch it, you're teaching them that repair is always available. That connection is always accessible. That a hard moment doesn't end the story.",
      "Miss it, and they wander away to sort through the rupture on their own. They invent stories. About what just happened. About what it means about them. About whether they're the kind of kid who pushes people away. About whether you're the kind of parent who stays mad. About their own worth. None of those stories are true. But middle schoolers are excellent at writing stories in the absence of better information, and a missed repair leaves a vacuum that those stories rush to fill.",
      "So you meet them there.",
      "Yes, they slammed the door. Yes, they were wrong. Yes, you were owed an apology. None of that matters for the next four seconds.",
      "Two wrongs don't make it right. And being right doesn't make them feel safe.",
      "You catch their eye. You give them the soft smile that says Oh hey, I'm so glad you're back. You amplify it. You lean in for the hug. You chuckle at the half-funny comment. You ask them to come sit down.",
      "You don't make them earn it. You don't pretend nothing happened. You don't bring it up either. The conversation about the fight can wait. The repair has to happen first.",
      "Here's the part of this that's actually hard.",
      "The work isn't in the moment of repair. Once you see it, you can't unsee it, and your instincts will know what to do. The work is being awake enough, regulated enough, and uncluttered enough to notice the four seconds when they happen.",
      "Which means you are the variable here, too.",
      "The next time a fight ends and your kid storms off, don't pick up your phone. Don't start drafting the speech you're going to give them later. Don't run the loop of I can't believe they said that to me. Stay in the room. Stay available. Keep your face soft.",
      "Wait.",
      "Because they're coming back. Sooner than you think.",
      "Every time you catch this moment, you teach them something they will carry forever:",
      "Coming back is safe.",
      "Being loved doesn't depend on getting it right.",
      "You are not too much.",
      "You're mine, and I'm yours.",
      "That's the language they don't have yet for what they're trying to say when they wander into your room. So you say it back to them, without saying it — with a smile, an open arm, and a complete absence of I told you so in your voice.",
      "The voice you want them to hear in their head twenty years from now, when they're standing in their own kitchen after a hard moment with someone they love, is the voice you're building right now. The one that says come back, it's safe here.",
      "Decide today that you'll be there for the four seconds.",
    ],
  },
  {
    slug: 'stop-reminding-start-collaborating',
    title: "Executive function isn't built through reminders",
    date: '2026-06-12',
    type: 'essay',
    topic: 'autonomy',
    tag: 'Newsletter · 9 min read',
    readTime: '9 min read',
    excerpt: "The hundredth reminder doesn't work because reminders were never going to build the skill in the first place.",
    dek: "The hundredth reminder doesn't work because reminders were never going to build the skill in the first place.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'your-kid-already-knows'],
    body: [
      "If you looked at your middle school kid this week and said \"I don't know how many times I have to tell you,\" and he still didn't do the thing — you don't have an obedience problem. You have an executive function problem. And it's not really a problem. It's a developmental gap. One your frustration is making worse.",
      "It doesn't matter that you said it a hundred times. You're saying the wrong thing.",
      "Reminders can't build the skill you're trying to build. The skill is internal, and reminders are external. The hundredth one will fail for the same reason the first one did.",
      "Let me define something. Executive function is the emerging skill that lets adolescents organize themselves toward a goal — plan, sequence, anticipate, follow through. It lives in the prefrontal cortex, the slowest-maturing part of the brain, the part that doesn't fully come online until somewhere around twenty-five.",
      "Here's the part that matters tonight: when you yell, the prefrontal cortex steps aside.",
      "The amygdala — the brain's threat sensor — takes over. Your kid's brain stops trying to solve what's my next step? and starts trying to solve how do I get out of this moment? He stops accessing the part of his brain that does goal-directed behavior and shifts into survival mode. Fight, freeze, shut down, deflect.",
      "That's why yelling about the backpack on the floor produces a fight, or a slammed door, or a flurry of reactions — but never substantial behavior change. You're recruiting the wrong part of his brain. You're asking the part that doesn't plan to suddenly start planning, while you actively scare the part that can plan into hiding.",
      "What we actually want is a regulated, thoughtful kid quietly narrating to himself: How am I doing? What's next for me?",
      "That voice is the whole game. Once it's there, you don't have to be there. Once it's there, he picks up his own backpack — not because you told him a hundred and one times, but because the internal monologue is doing the work the reminder used to do.",
      "So how does that voice get built?",
      "Not reactively. The reminder is reactive — it shows up after the skill has already failed. Executive function is proactive by nature. It plans toward something. It can't be installed by interrupting the moment it's missing.",
      "It gets built one way: through repeated patterns of collaborative thinking that the kid eventually internalizes as his own.",
      "This is old developmental psychology. Vygotsky figured it out almost a century ago — the inner voice a kid uses to talk himself through a hard task starts as the outer voice of the adult who used to talk him through it. The conversations you have with him become the conversations he has with himself. If those external conversations are mostly \"I told you to —\" and \"how many times do I have to —\", that's the internal voice you're building too.",
      "If they're regulated, collaborative, and curious — that's the internal voice instead.",
      "So instead of the reminder, try the question.",
      "Stay calm. Make eye contact. Lower your voice if anything.",
      "\"What do you still have left to do today?\"",
      "\"What's your plan for getting that done?\"",
      "\"What might get in the way?\"",
      "\"Do you want to do that before dinner or after practice?\"",
      "\"What's the first step?\"",
      "These aren't magic sentences. They're not a script that produces a regulated kid the first time you read them off your phone. They're the same moves you want him to learn to make for himself, performed out loud so he can borrow them. You are the scaffolding. The scaffolding comes down eventually. But not before the structure can stand on its own.",
      "Over time, those external conversations become internal ones. And that's the whole point.",
      "Executive function isn't built through reminders. It's built through patterns — the kind that repeat enough that the kid stops needing the parent to start them.",
      "That means you are the variable. Not him.",
      "The fastest way to slow this down is to keep doing the thing that keeps not working, only louder. The fastest way to speed it up isn't a new chore chart or a sticker system or a sit-down about responsibility. It's choosing, tonight, to swap one reminder for one question. To stay regulated when every instinct in your body is telling you to escalate. To say \"what's your plan?\" instead of \"I told you already.\"",
      "You'll have to do it more than once. Probably more than a hundred times. But each one of those reps is the rep the reminder reps never were — because each one is building the skill instead of working around it.",
      "Tonight, do one thing.",
      "Find the next moment you feel the familiar reminder rising in your chest — the laundry, the homework, the dishes, the bag by the door. Don't say it.",
      "Take a breath. Lower your shoulders. Ask one question instead: What's your plan for that?",
      "Then let the answer sit. Even if it's a shrug. Even if it's a sigh. Even if it's nothing.",
      "The voice in your kid's head is going to be your voice one day. Decide now what you want it to sound like.",
    ],
  },
  {
    slug: 'its-an-inside-job',
    title: "It's an inside job. You can't get inside.",
    date: '2026-06-06',
    type: 'essay',
    topic: 'emotional-literacy',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "The number one concern for American parents is their child's mental health. Here's what we actually control.",
    dek: "The number one concern for American parents is their child's mental health. Here's what we actually control.",
    img: null,
    featured: true,
    related: ['when-they-cant-name-it', 'its-cool-to-care'],
    body: [
      "I finally got back on the calendar with my therapist last week. He could tell I was carrying a lot. Visible and verbal weight were on my face and chest.",
      "\"I'm just feeling…lonely.\" As we unpacked it, so much of what was barring my connection was helplessness. I felt unable to help, support or change pain for people around me, and it weighed on me.",
      "There's an incredible loneliness that happens in our life when we can't fix something for someone we love. It's like we're standing at a locked door trying to communicate with them through the door. Barking instructions, resisting the urge to break it down.",
      "There's this urgency and restraint that combine into a pain we can't really describe except through a sigh and clenched jaw.",
      "As parents, we picture ourselves in this analogy on the outside of the door, our kids inside. And many of us feel like we're living that reality, every day. Access to our kids' inner lives feels fleeting, emotional firewalls fly up with phones and shrugs.",
      "We extrapolate. We presume a lack of communication to be a sign of anxiety and depression, disconnection and purposelessness.",
      "The number one concern for American parents is the mental health of their child. Over 50% of American parents have significant fear about the mental health of their kid.",
      "That's because we understand what it means to be on both sides of the door.",
      "Parents, we've been trapped in our heads with anxiety. We've doomscrolled through the depression of world affairs. We've wrestled with futility and purpose. The empathy we have for a child walking into that world creates a distressing urgency inside of us.",
      "\"Get them to safety.\" We think, but we can't guarantee it, completely. Those instincts are generous, but misplaced.",
      "Because having been inside those feelings, we all know that the only way we get to stability is tools, support, and agency. It's a three legged stool.",
      "Instead of dismay, we can parent with more clarity.",
      "We are the first source of tools our children have to understand their inner life. The way we communicate, repair. We teach them how to communicate in conflict, distress, joy, growth, and failure. These are the maps that our kids will take with them.",
      "We are the first source of support. We prioritize connection. We challenge them, and scaffold the inner voice. We teach them what it feels like to be seen, safe and supported.",
      "But we aren't the third leg, and we can't be. We aren't their agency. And the third leg is what's emergent in adolescence, and the only way that they can understand the importance of their own process is if we prioritize it for ourselves.",
      "Try this this weekend: do the thing you've been putting off for your own inner life — book the appointment, take the walk, say the hard true thing out loud — and let your kid see you do it. You're showing them the door opens from the inside.",
    ],
  },
  {
    slug: 'its-cool-to-care',
    title: "Apathy isn't a character flaw. It's armor.",
    date: '2026-05-30',
    type: 'essay',
    topic: 'relationship',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "When your kid shrugs at the thing they used to love, they're not telling you who they are. They're telling you what they're protecting.",
    dek: "When your kid shrugs at the thing they used to love, they're not telling you who they are. They're telling you what they're protecting.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'take-care-of-your-own-backyard'],
    body: [
      "My high school students used to call me a try-hard. \"Mr., you're crazy, dude. Such a try-hard.\"",
      "I'd say, \"Absolutely. 100%. I'm a try-hard.\"",
      "Because what they were actually doing in those moments wasn't insulting me. They were probing. Trying to figure out why I cared. Because the dominant social posture among middle schoolers and teenagers is apathy — and apathy is a social skill, not a character flaw.",
      "Here's what I mean. When a kid says \"I don't care,\" they are usually doing one of three things: they are protecting themselves from looking like they tried and failed. They are protecting their autonomy from adults who have been telling them what's important for as long as they can remember. They are protecting themselves from a world that, honestly, looks pretty overwhelming from the inside of a 12-year-old's phone.",
      "**Apathy is armor.** It's a way of saying \"you can't disappoint me, you can't control me, and I refuse to be naive.\" In a developmental phase defined by hyper-vigilant social scanning — where every move is being watched and graded — caring out loud is genuinely risky. Effort is exposure. And if you've been burned once, the cheapest way to never get burned again is to perform not caring.",
      "So when your kid shrugs at the thing they used to love, or rolls their eyes at the project they secretly worked hard on, or says \"whatever, it's stupid\" about something that clearly mattered an hour ago — they are not telling you who they are. They are telling you what they are protecting.",
      "The job is not to lecture them out of it. You can't argue a kid into caring. The harder you push, the more the armor hardens, because now caring means siding with you against their own social instincts.",
      "The job is to model that effort and enthusiasm is not embarrassing. That it's actually cool to care. That the adults they trust are people who try at the things that matter to them.",
      "This week, let your kid see you care about something. Not perform it, not lecture about it. Just be visibly enthusiastic about something — your work, a hobby, a friendship, a problem you're trying to solve — and let them watch you stay with it when it's hard. No commentary required. You're not trying to convince them caring is good. You're showing them what it looks like.",
    ],
  },
  {
    slug: 'the-slow-kid',
    title: "I've spent years trying to fix the slow kid. I think the slow kid is trying to fix me.",
    date: '2026-05-23',
    type: 'essay',
    topic: 'resilience',
    tag: 'Newsletter · 3 min read',
    readTime: '3 min read',
    excerpt: "Yelling at your kid to hurry up is the thing slowing your morning down. Here's the neuroscience — and a different way in.",
    dek: "Yelling at your kid to hurry up is the thing slowing your morning down. Here's the neuroscience — and a different way in.",
    img: null,
    featured: false,
    related: ['your-kid-already-knows', 'take-care-of-your-own-backyard'],
    body: [
      "I've spent years trying to fix the slow kid. I'm starting to think the slow kid is trying to fix me.",
      "One of my sons wakes up later than everyone, quietly wanders into the shower, takes too long. Last to be dressed, last to get breakfast, last in the car. Some mornings I've handled it well. Some mornings I haven't. I've tried timers, scaffolds, every strategy in the comments section. We're all stuck in the same loop.",
      "The other day I was working hard not to lose it. The win in those moments, for me, isn't being on-time. The win is not creating more harm. And while I was standing in the kitchen, quietly boiling, I had a thought I haven't been able to put down.",
      "What if he's right to be this slow? What if I'm the crazy one for being so beholden to the clock?",
      "Part of his pace is just who he is — attention span, personality, fatigue, all of it mixed in. But part of it, I think, is his nervous system trying to teach me: this pace is not good for us.",
      "Chronic urgency isn't neutral. It's a low-grade stress dose, repeated daily, and the research on it is unambiguous. Sustained activation of the stress system — cortisol elevated for hours, every morning and evening — is associated with sleep disruption, attention dysregulation, anxiety, and long-term cardiometabolic risk. Adults know this. We've named it: burnout. We treat it as a crisis when it shows up at work. We rarely name its infancy when it shows up in our kitchens.",
      "My slow kid isn't broken. He hasn't yet learned to override his body. He hasn't built the calluses yet that let an adult run on cortisol from 6 AM to 9 PM and call it normal. His resistance to the fire drill isn't immature or irresponsible. **It's a productive adaptation to a culture that is, in measurable ways, killing the adults inside it.**",
      "And before you say, \"But I don't have time…\", remember: escalating into urgency makes everything worse. When I yell at the slow one, his amygdala kicks on and his prefrontal cortex — the part responsible for sequencing, planning, and finishing the next task — goes offline. That's not a metaphor. It's the brain prioritizing survival over execution. Yelling about the shoes does not produce the shoes. It produces a fight, a flurry, a frozen kid, and a slower morning. The intensity I was using to get him moving is the exact thing keeping him stuck.",
      "So I'm not arguing with the schedule. School starts when it starts. The schedule isn't the variable — our intensity is. A morning can run on time without running on emergency. The fire drill isn't built into the clock; it's built into us. And our kids are watching us model what an acceptable adult life feels like in the body. When every morning starts in cortisol, we're teaching them that adulthood is something you survive at high speed.",
      "I'd like to teach them something else.",
      "Try this tomorrow morning: when the slow one is being slow, before you reach for the clock, slow down yourself. Drop your shoulders. Lower your voice. And ask one normal question — *Hey bud, where are you at?* You're doing two things at once. You're calming your own cortisol so you can actually think. And you're telling your kid that he matters more than the calendar.",
      "Sometimes the slowest body in the room is the wisest one. Not because time isn't real. Because we're not the standard he should be calibrating to.",
    ],
  },
  {
    slug: 'your-kid-already-knows',
    title: "Your kid already knows.",
    date: '2026-05-16',
    type: 'essay',
    topic: 'communication',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "Every time you try to prove you're right or drive the point home, you're robbing them of the chance to draw that conclusion themselves.",
    dek: "Every time you try to prove you're right or drive the point home, you're robbing them of the chance to draw that conclusion themselves.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'when-they-cant-name-it'],
    body: [
      "Every time you try to fix the situation. Every time you try to prove you're right. Every time you make sure they understand the seriousness of what they did — you're robbing them of the chance to draw those conclusions on their own.",
      "Here's what I know about the parents reading this. You've installed the structure. You've modeled the values. You've had the conversations a hundred times. Your kid can tell the difference between right and wrong. They know when they've crossed a line. They know when they're disconnected from you. The intuition is in there.",
      "We all have this. I know I should go to the gym. I know I shouldn't eat the cookie. I know I should call my brother. We all carry a quiet inner voice that tells us the right thing to do.",
      "But think about how it lands when your spouse turns to you and says, \"You don't need to be eating that cookie.\"",
      "Don't tell me what to do. I know. Of course I don't need to be eating this cookie. I'm bored, today kind of sucked, and I'm eating it anyway.",
      "Now your intuition isn't speaking to you. It's reacting to them. It's not giving you clarity or guidance — it's just defending itself.",
      "**That's what's happening when we react fast and talk too much with our kids.** Their intuition was about to kick in. They were about to think \"I need to sit with this for a second.\" And then we filled the space. We delivered the lesson, named the consequence, made sure they understood the seriousness.",
      "And now their developing inner voice — the one we've been trying to build for thirteen years — gets shoved aside so they can react to us instead.",
      "This is the developmental piece a lot of parents miss. That intuition we have, that on-demand reflective process? Our middle schoolers don't have it yet. Not the way we do. It takes them a beat. Sometimes a long beat. They have to feel the weight of the moment, register the disconnection, and let their own values catch up.",
      "**That beat is the entire skill.**",
      "When we react fast, we don't just miss the moment — we replace it. Their internal process becomes external conflict with us. And the next time something goes wrong, their intuition is even quieter, because it's been trained to wait for our voice instead of its own.",
      "I'm not saying don't have boundaries. Boundaries are right. Hold the line. But once the line is held, get out of the way.",
      "This week, try this: when your kid does the thing — the rude tone, the missed chore, the dumb decision — say less than you want to. Hold the boundary, name it once, and then stop. Give them sixty seconds of nothing. No follow-up. No clarification. No making sure they got it.",
      "They got it. Let their intuition do the work it was built to do.",
    ],
  },
  {
    slug: 'take-care-of-your-own-backyard',
    title: "Take care of your own backyard.",
    date: '2026-05-09',
    type: 'essay',
    topic: 'reflection',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "It took me 20 years, hundreds of students, and 3 kids to understand what my mother meant.",
    dek: "It took me 20 years, hundreds of students, and 3 kids to understand what my mother meant.",
    img: null,
    featured: false,
    related: ['autonomy-grows-in-the-space', 'its-cool-to-care'],
    body: [
      "As an impassioned 22-year-old volunteer teacher I was ready to fix the world in a year.",
      "My mother slowed me down with six words from her grandfather — a career restaurateur and barman who greeted the world with a smile and conversation — \"Take care of your own backyard.\"",
      "It took me 20 years, hundreds of students, and 3 kids to realize what she meant.",
      "My mother was a child development major — a major she invented with the dean inside Boston College's Carroll School of Education because she wasn't going to be a teacher or social worker, and her course selection evaded classification. She worked with adults with disabilities before moving 3 times with 3 young kids took over our lives. She knew the psychology and development frames, and had the training that made me later ask her \"Why don't you run a school?\" She didn't need scripts, routines, and frameworks because she had something better: she had agency and intent.",
      "In a single look your direction, she was resilient, patient, gentle and demanding. Her love was the grace and space that allowed us to feel safe in our mess, and a quiet confidence that we would do the right thing for others and in so doing find ourselves.",
      "**What she meant, when she reminded me to \"take care of my own backyard,\" was that the single most important thing I controlled was the way I showed up every day** — because the measure of a life is in human relationship.",
      "We give them our full attention. We are grateful for all parts of them. We don't worry about the return or the outcome because the giving is the living.",
      "She never said any of this to me. She just taught it to me when she sat in the dark with me and listened. You can do that too — it's simpler than you realize.",
      "So try this this week: give yourself permission to leave your phone in the other room, sit at the dinner table with your kids for way too long. Or sit on their bed in the dark well past lights out, and listen. And when you see them next, just be glad they are there.",
    ],
  },
  {
    slug: 'when-they-cant-name-it',
    title: "When they can't name it, they blame it.",
    date: '2026-05-02',
    type: 'essay',
    topic: 'emotional-literacy',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "There are 3,000 words for feelings in English. Our kids have access to maybe twelve. Here's what happens when the vocabulary runs out.",
    dek: "There are 3,000 words for feelings in English. Our kids have access to maybe twelve. Here's what happens when the vocabulary runs out.",
    img: null,
    featured: false,
    related: ['its-an-inside-job', 'your-kid-already-knows'],
    body: [
      "When emotional vocabulary is thin, the nearest person becomes the cause of discomfort.",
      "A hangry kid will look you dead in the eye when you ask them to set the table and say, \"YOU DON'T THINK I CAN DO ANYTHING RIGHT?!\" Then, twenty minutes after dinner, you ask them to help with the dishes and they say, \"Of course.\"",
      "We laugh at that one because it's familiar. But the same misfire happens in subtler, more damaging ways every week. A kid is frustrated by a new assignment and blows up on their brother for walking in the room. A kid feels embarrassed when they miss an instruction in class and decides the teacher hates them. A kid is exhausted by your perfectly reasonable feedback and decides you're trying to ruin their life. And you're left holding the bag, wondering what just happened.",
      "Here's what's actually happening: **when a kid can't name what they're feeling, they default to blame.** Whoever made the demand becomes the source of the dysregulation. You asked for the table to get set, so you must be the problem. The teacher gave the instruction, so the teacher must hate them. The brother walked in the room, so the brother must be annoying.",
      "Blame is the dead giveaway of a missing skill.",
      "When emotional intelligence is online, a kid can pause and recognize, *I'm uncomfortable, and that discomfort is mine to manage.* When it isn't, the discomfort has to come from somewhere — so they look around and assign it to the nearest available person. Usually you.",
      "This isn't manipulation. It isn't disrespect. It's a kid grabbing the closest available label for a feeling they don't have words for, and then building a story on top of that label like it's the truth. There are 3,000 words for feelings in English, and our kids have access to maybe twelve. So *mad* and *unfair* and *you* do a lot of heavy lifting they shouldn't have to do.",
      "If you can hear the blame as a signal — not as an accusation — the whole interaction changes. You stop defending yourself and start scaffolding the skill they're missing.",
      "You can't tell a kid \"you're feeling the wrong thing\" in the moment. That's a fight you'll lose. But you can come back to it later.",
      "Try this: tonight or this week, after the storm passes, go back to a recent blowup and ask, \"What do you think you were actually feeling right then? Because you caused some harm thinking everyone was out to get you.\" Then sit in the silence — don't rescue them. Let them try a word. If it's wrong, offer two more: \"Could it have been embarrassed? Frustrated? Tired?\" You're not interrogating. You're offering vocabulary in multiple choice.",
      "That replay and reflection is where the skill gets built. One quiet conversation at a time. The kid who learns to catch their own blame reflex becomes a better partner, a better sibling, a better friend, and eventually a much better adult.",
      "It's a skill. It can be learned, and our kids will be better people for it.",
    ],
  },
  {
    slug: 'autonomy-grows-in-the-space',
    title: "Autonomy grows in the space we don't occupy.",
    date: '2026-04-25',
    type: 'essay',
    topic: 'autonomy',
    tag: 'Newsletter · 2 min read',
    readTime: '2 min read',
    excerpt: "My son is batting .090 and loves baseball more than any sport in the world. The reason is his coach — and what his coach doesn't do.",
    dek: "My son is batting .090 and loves baseball more than any sport in the world. The reason is his coach — and what his coach doesn't do.",
    img: null,
    featured: false,
    related: ['your-kid-already-knows', 'its-cool-to-care'],
    body: [
      "My son is batting about .090 this season. And he loves baseball more than any sport in the world right now.",
      "He's been working at it. Watching YouTube. Hitting balls in the yard. Swinging his bat full speed in the kitchen while I'm trying to cook.",
      "This weekend, he hit his first real double, and doubled down on the work after.",
      "The only reason he's still in it is his coach. A guy who has stayed patient, curious, stayed collaborative, and has always found a way for my son to contribute to the team outside of the batter's box.",
      "My job? Resisting every coaching instinct I have. Staying curious. Giving him the autonomy to chase the thing he is naturally motivated to chase — hitting baseballs.",
      "And here's what I keep coming back to: in middle school, what our kids want more than almost anything is to understand their own agency. Their own power. To feel like the things they care about are theirs, not assigned. **And that feeling will never come from our instructions. It can only come from the space we leave for it.**",
      "Research on adolescent motivation backs this up — kids this age are wired to protect autonomy and resist feeling controlled, even when the \"control\" is well-meaning coaching from the people who love them most. The more we steer, the more we communicate that the thing isn't really theirs.",
      "Our influence is real, but it's quieter than we think. We don't author who our kids become. What we do shape is the environment around them. The spaces they move through. The people they're around when we're not there. The conditions that let them find the version of themselves they actually like being.",
      "I notice it with my oldest. When the inputs are right — the right friends, enough sleep, real things to care about — the kid is a joy. Not because I'm enjoying him. Because he is enjoying him. And I get to watch that.",
      "We all have a version of ourselves we're our best in. For me it's family and old friends and food on a table. For my wife, it's something else entirely, and I love watching her find it. Our kids deserve the same — a chance to find the rooms, the people, the activities where their best self shows up without being summoned.",
      "Our job isn't to define that for them. It's to leave room for it. To encourage the pursuit. To resist the instinct to coach the swing when what they actually need is the space to keep learning.",
      "This week, try this: the next time your kid finishes a practice, a game, a hard test, a rough social moment — don't lead with feedback. Don't lead with questions either. Try \"Good to see you,\" and let the silence sit.",
      "And when you do talk about the thing they're working on, swap the coaching sentence for a curious one. Instead of \"You should…\" or \"Next time, try…\", try: \"What are you working on?\" \"What do you want to try next?\" \"What's the hard part?\" Same situation. Different approach. Because the thing most middle schoolers rarely feel from their parents is this: **that being around you isn't an evaluation, and autonomy grows in the space we don't occupy.**",
    ],
  },
];
