// Add new letters to the TOP of this array (newest first).
// Type: 'essay' (longer, 5+ min read) | 'note' (2-4 min, Saturday note)
// Body: array of paragraph strings. Use ** for **bold**.

export const LETTERS = [
  {
    slug: 'i-taught-middle-school-twelve-years',
    title: 'I taught middle school for twelve years. Then I had three sons.',
    date: '2026-01-12',
    type: 'essay',
    topic: 'emotional-literacy',
    tag: 'Essay · 11 min read',
    readTime: '11 min read',
    excerpt: "What the classroom got right about kids that the parenting books got wrong — and the six practices I brought home with me.",
    dek: "What the classroom got right about kids that the parenting books got wrong — and the six practices I brought home with me.",
    img: '/images/sean-teaching.jpg',
    featured: true,
    related: ['be-the-weather', 'inspect-dont-expect', 'bad-moment-great-opportunity'],
    body: [
      "I spent twelve years in room 201 — a corner classroom in a Chicago middle school with a stubborn radiator and thirty-one chairs I rearranged every week, hopefully, with strong opinions. Seventh graders are widely considered the worst people on earth. I considered them some of the best.",
      "They will tell you the truth about your lesson before you've finished writing the date on the board. They are, under all that noise and drama, genuinely trying. They want to be good at things. They want adults to believe they can. **What I learned in twelve years was simple: kids do not rise to what you wish for them. They rise to what you build, name, and inspect.**",
      "When my first son Henry was born, I parented him the way most people do — by guessing. We read the books. Did the bedtimes. Bought the wooden toys. He turned out mostly fine. Then his brother Sam came along, and three years later Theo, and I noticed something embarrassing: I was a better teacher than I was a parent.",
      "The worst parts of my parenting were the parts where I'd forgotten to be the adult I was at school. I was wishing where I should have been inspecting. Reacting where I should have been pausing. Lecturing where I should have been modeling.",
      "So I took six practices home. I wrote them on an index card on the fridge. I taught them to my sons the way I'd taught poetry to a hundred seventh graders — embarrassingly explicitly, with humor, with patience, and with the underlying belief that they were capable of learning them. They were. They all are.",
      "Those six practices are what this newsletter is about. They are not original. None of them are mine. I borrowed every single one from someone better. What I did was sand them down to the version that works with three boys on a Tuesday when everyone is tired and dinner is burning.",
      "I'll write about each one. I'll show you what it looks like at 7am with a packed lunch on the counter. I'll give you the exact script — the words I say, in the order I say them, with the result I'm aiming for. Because that's what worked in the classroom. Specificity. Not principles. Practices.",
    ],
  },
  {
    slug: 'be-the-weather',
    title: "Be the weather: why the parent's mood is the family's climate",
    date: '2026-01-26',
    type: 'essay',
    topic: 'resilience',
    tag: 'Essay · 7 min read',
    readTime: '7 min read',
    excerpt: "If you bring a storm, you'll get a storm back. Every time. The most important practice, written plainly.",
    dek: "If you bring a storm, you'll get a storm back. Every time. The most important practice, written plainly.",
    img: null,
    featured: false,
    related: ['use-the-cooler', 'inspect-dont-expect'],
    body: [
      "Here is the most important thing I learned in twelve years of teaching, and it took me five of those years to see it clearly: **the adult sets the weather in the room.** Not the kids. Not the lesson. Not whether it's Friday or Monday or the week before spring break. The adult.",
      "I had a colleague named Mrs. Torres who taught next door to me for six years. She had the same kids I had — same age, same school, same neighborhood. Her room was quieter. More focused. Kids went in there stressed from whatever happened at lunch and came out regulated. I went in to borrow a stapler once and just... stayed for ten minutes, because the room felt good.",
      "What she had wasn't a trick. It was a posture. She walked in calm. She spoke at the same pace whether the room was quiet or chaotic. She never matched the energy of a bad moment. She brought her own energy, and the room eventually matched her.",
      "**The mood you carry is the climate they live in.** This is not metaphor. It is neuroscience — mirror neurons, co-regulation, the way a calm nervous system literally down-regulates the nervous systems around it. But you don't need to know the science to use it. You just need to pause at the door.",
      "Three breaths before you walk in. One sentence: *What kind of room do I want this to be?* Then walk in like the answer is already true.",
      "That's the whole practice. It sounds too simple. It isn't. It is the hardest thing I do as a parent, on the days when I'm tired and behind and the kitchen is a disaster and someone is crying about something that happened at school. **The temptation is to match the chaos. The practice is to not.**",
    ],
  },
  {
    slug: 'inspect-dont-expect',
    title: "What 'inspect, don't expect' looks like at 7am with three kids and a packed lunch",
    date: '2026-04-12',
    type: 'essay',
    topic: 'reflection',
    tag: 'Essay · 8 min read',
    readTime: '8 min read',
    excerpt: "The unsexy logistics of standards — a Tuesday morning, photographed.",
    dek: "The unsexy logistics of standards — a Tuesday morning, photographed.",
    img: null,
    featured: false,
    related: ['three-to-one', 'i-do-we-do-you-do'],
    body: [
      "It is 7:04am on a Tuesday and I am standing in the kitchen doorway watching Henry (11) shove his lunch box into a backpack that is already too full. The backpack will not close. He is not looking at the backpack. He is looking at his phone.",
      "This is a moment. I have two options.",
      "**Option one:** I say *Henry, your backpack isn't going to close like that, and why are you on your phone.* This is expectation. I am hoping that stating the problem causes the problem to be solved. It will not. It never does. He will look up, look annoyed, possibly say something that starts an argument we don't have time for.",
      "**Option two:** I walk over. I put my hand on the backpack. I say *show me what's in here.* This is inspection. We open the bag together. There are three library books he meant to return last week. We take them out. The bag closes. I hand him the library books and say, cheerfully, *these go on the counter, we'll figure it out tonight.* He nods. The moment ends.",
      "The difference between these two options is not dramatic. But repeated five hundred times over the course of a year, it is the entire difference between a house where standards exist and a house where standards are just wishes.",
      "Inspection is not surveillance. It is not punishment. It is the act of actually looking at the thing you care about. **What you inspect, you raise. What you only expect, you lower** — because every time you say a standard and don't follow through with a look, you are teaching the kid that the standard is optional.",
      "The script is simple: *Show me.* Two words. Cheerful, not interrogating. Show me your plate. Show me your homework. Show me your shoes. Show me how you left the bathroom. Specific enough that there's nothing to argue about, because you're both looking at the same thing.",
    ],
  },
  {
    slug: 'three-to-one-explained',
    title: "Three to one, explained: a teacher's ratio for praise that actually builds resilience",
    date: '2026-03-15',
    type: 'essay',
    topic: 'relationship',
    tag: 'Essay · 12 min read',
    readTime: '12 min read',
    excerpt: "Why three observations of growth for every correction is the only feedback rule that survives contact with a 9-year-old.",
    dek: "Why three observations of growth for every correction is the only feedback rule that survives contact with a 9-year-old.",
    img: null,
    featured: false,
    related: ['bad-moment-great-opportunity', 'i-do-we-do-you-do'],
    body: [
      "I learned about the three-to-one ratio from a reading specialist named Dr. Elkins who came to our school in 2013 to help us with struggling readers. She was talking about feedback on a reading passage. She was not talking about parenting. But I wrote it on a Post-it and stuck it to my desk and I have thought about it almost every day since.",
      "The ratio: **three specific observations of growth for every one correction.** Not three compliments. Not three nice things. Three observations of *process* — of effort, of strategy, of improvement. The correction can be anything, but it has to follow three things that are true.",
      "The reason this works is not complicated. A kid who receives a correction in a field of silence — where no one has said anything good — hears the correction as *you are failing at this.* A kid who receives the same correction after three genuine observations of what they're doing right hears it as *you are growing at this, and here is the next step.* The information in the correction is identical. The experience of receiving it is completely different.",
      "What counts as an observation of growth? Not: *good job.* Not: *you're so smart.* Those are trait labels. They inflate the ego without teaching anything. What counts: *You tried it a different way when the first way didn't work. That's exactly the muscle.* Or: *You asked for help before you got frustrated. That's new. I noticed.* Or: *You finished it. You didn't want to and you finished it anyway.*",
      "**Name the behavior, not the kid.** The kid will hear it as identity — *I am someone who does that thing* — which is exactly what you want. Not *you're smart,* which is fragile. But *you showed up when it was hard,* which is a story they can tell themselves next time.",
    ],
  },
  {
    slug: 'bad-moment-great-opportunity',
    title: 'Bad moment, great opportunity: the repair that actually teaches something',
    date: '2026-04-05',
    type: 'essay',
    topic: 'communication',
    tag: 'Essay · 9 min read',
    readTime: '9 min read',
    excerpt: "Meltdowns are feedback loops. The repair afterward is the actual lesson.",
    dek: "Meltdowns are feedback loops. The repair afterward is the actual lesson.",
    img: null,
    featured: false,
    related: ['use-the-cooler', 'be-the-weather'],
    body: [
      "Last October I yelled. Not a little. At Theo (7), over something small — I don't even remember what now, which tells you everything. He cried. I went to my room. I sat on the edge of the bed and felt like the worst person on earth for about four minutes.",
      "Then I went back out.",
      "I said: *I lost it. That wasn't okay. Here's what I should have done — I should have said I was frustrated and needed a minute, and walked away. Instead I yelled, and that's on me.* He was still teary. I said: *Can we try the rest of the night again?* He nodded. We did.",
      "That five-minute conversation taught him more than a hundred smooth evenings would have. It taught him that adults can be wrong and say so. It taught him that rupture is not permanent. It taught him — by watching me model it — what repair looks like. **The lesson lives in the apology, not the argument.**",
      "This is the sixth practice and it might be the hardest, because it requires you to go back toward the thing you want to be done with. The fight is over. The kid has calmed down. You are tired. The last thing you want to do is reopen it. But the repair is where the learning actually happens — for both of you.",
      "The window is two hours. After that the moment is too far gone, and the repair feels like dredging rather than closing. Within two hours, while everyone still remembers the feeling but has regulated past it: that's when you go back.",
      "The script: *I lost it earlier. Here's what I should have done. Can we try the rest of tonight again?* Three sentences. That's it. You don't need to over-explain. You don't need to make it a lesson. The act of returning is the lesson.",
    ],
  },
  {
    slug: 'on-the-difference-between-a-rule-and-a-ritual',
    title: 'On the difference between a rule and a ritual',
    date: '2026-04-26',
    type: 'note',
    topic: 'reflection',
    tag: 'Saturday note · 3 min read',
    readTime: '3 min read',
    excerpt: "A rule is what you enforce. A ritual is what you build together. They look similar on the outside.",
    dek: null,
    img: null,
    featured: false,
    related: ['inspect-dont-expect'],
    body: [
      "A rule is what you enforce. A ritual is what you build together. They look similar on the outside — both involve the same behavior, at the same time, with some kind of consequence if it doesn't happen.",
      "The difference is ownership. A rule lives in you, the parent. A ritual lives in both of you. The kid who follows a rule does it because you're watching. The kid who participates in a ritual does it because it's *ours.*",
      "**The practical implication:** if you want a behavior to stick, turn the rule into a ritual before you try to enforce it. What does *ours* look like? Usually it means the kid helped design it, or helped name it, or has some say in the when or the how. Not the whether — you can own the whether. But the shape of the ritual? That's negotiable.",
      "This week, pick one rule in your house that isn't sticking. Ask the kid what would make it feel less like a rule. You might get a surprisingly workable answer.",
    ],
  },
  {
    slug: 'the-two-minute-repair-script',
    title: 'The two-minute repair script we use after every rupture',
    date: '2026-04-05',
    type: 'note',
    topic: 'communication',
    tag: 'Saturday note · 2 min read',
    readTime: '2 min read',
    excerpt: "Three sentences. That's the whole script. I use it every time.",
    dek: null,
    img: null,
    featured: false,
    related: ['bad-moment-great-opportunity'],
    body: [
      "Three sentences. That's the whole script. I use it every time, whether the rupture was big (I yelled) or small (I was dismissive, or I wasn't listening).",
      "**One:** *I [did the thing].* Specific, not general. Not *I was in a bad mood.* But *I raised my voice when you were already upset, and that made it worse.*",
      "**Two:** *What I should have done was [the thing I wished I'd done].* This is the teaching part. You're modeling what the better move looks like, in real time, without pretending you got it right.",
      "**Three:** *Can we try the rest of [tonight/this morning/this week] again?* This is the offer. It's a reset. Most kids will say yes, because most kids want the reset too.",
      "The repair doesn't undo what happened. It teaches something better: that grown-ups can be wrong, that relationships can be repaired, and that the relationship is more important than being right.",
    ],
  },
  {
    slug: 'why-i-stopped-saying-good-job',
    title: "Why I stopped saying 'good job' — and what I say instead",
    date: '2026-03-29',
    type: 'note',
    topic: 'relationship',
    tag: 'Saturday note · 3 min read',
    readTime: '3 min read',
    excerpt: "'Good job' is a trait label. It doesn't tell the kid anything about what they did.",
    dek: null,
    img: null,
    featured: false,
    related: ['three-to-one-explained'],
    body: [
      "'Good job' is a trait label. It doesn't tell the kid anything about what they did. It tells them something about what you think of them, which makes it powerful in the wrong direction — because now their identity is wrapped up in your approval rather than their own effort.",
      "I stopped saying it about five years ago, when I realized I was saying it the same way I said *nice weather* — a filler phrase, not a real observation. My kids knew I wasn't really looking. Kids always know.",
      "What I say instead: I describe what I saw. *You tried it a different way when the first way didn't work.* Or: *You didn't give up when it got hard. I saw that.* Or, simplest of all: *You finished it.* That's it. Just naming the act.",
      "The effect is real and measurable, if you're paying attention. **A kid who hears 'good job' 50 times a day learns to perform. A kid who hears specific observations of their effort 50 times a day learns to notice their own effort.** Which is the whole point.",
    ],
  },
  {
    slug: 'the-kitchen-table-debrief',
    title: 'The kitchen-table debrief',
    date: '2026-03-08',
    type: 'note',
    topic: 'resilience',
    tag: 'Saturday note · 4 min read',
    readTime: '4 min read',
    excerpt: "Ten minutes at the end of the day. No phones. One question.",
    dek: null,
    img: null,
    featured: false,
    related: ['be-the-weather'],
    body: [
      "Ten minutes. No phones. One question. That's the whole thing.",
      "We do it at the kitchen table after dinner, before anyone disappears. The question rotates — sometimes it's *one good thing, one hard thing,* sometimes it's *what surprised you today,* sometimes it's just *what do you want me to know.*",
      "The ritual isn't magic. Some nights the answers are one syllable. Some nights someone cries about something that happened three weeks ago that they've been carrying. You never know which kind of night it'll be, which is exactly why you do it every night.",
      "**The consistent container is the whole point.** If the debrief only happens when something seems wrong, the kids learn that it's an interrogation. If it happens every night regardless, it becomes the place where things get said. They start offering things you didn't know to ask about.",
      "Start tomorrow. Set a timer for ten minutes so you're not watching the clock. Ask one question. Be quiet after you ask it. The quieter you are, the more they say.",
    ],
  },
  {
    slug: 'on-meltdowns-mine-included',
    title: 'On meltdowns, mine included',
    date: '2026-03-01',
    type: 'note',
    topic: 'communication',
    tag: 'Saturday note · 3 min read',
    readTime: '3 min read',
    excerpt: "The most useful thing I can do after I lose my temper is say so.",
    dek: null,
    img: null,
    featured: false,
    related: ['bad-moment-great-opportunity', 'use-the-cooler'],
    body: [
      "I had a meltdown last Tuesday. Mine, not the kids'. I had a deadline, the house was loud, and Theo asked me the same question four times and on the fourth time I responded with more volume than the situation required.",
      "Here's what I've learned after years of practicing this: **the meltdown itself is not the problem. What you do in the next two hours is the problem — or the opportunity, depending on how you use it.**",
      "The most useful thing I can do after I lose my temper is say so. Not explain it. Not justify it. Just say it out loud to the kid who was on the receiving end: *I lost it. That wasn't okay.*",
      "Modeling emotional regulation doesn't mean never losing your temper. It means your kids get to see what it looks like to acknowledge a bad moment and come back from it. That's actually more valuable than perfect composure, which they'll never see in real life anyway.",
    ],
  },
  {
    slug: 'the-cooler-is-not-a-punishment',
    title: 'The cooler is not a punishment',
    date: '2026-02-09',
    type: 'note',
    topic: 'resilience',
    tag: 'Saturday note · 2 min read',
    readTime: '2 min read',
    excerpt: "Parents use the cooler too. That's the whole point.",
    dek: null,
    img: null,
    featured: false,
    related: ['use-the-cooler', 'be-the-weather'],
    body: [
      "The most common misread of the cooler: parents use it as a consequence for the kid. *Go to your room and cool off.* That's a time-out, and it works fine, but it's not what I'm talking about.",
      "**The cooler is a tool for the adult.** It's the deliberate pause *you* take before responding to the thing that just happened. I hear you. I need a minute. We'll talk in five. Then you actually take five.",
      "When you use it on yourself — in front of your kids — you are teaching them three things at once: that strong feelings are survivable, that you can choose your response instead of just having it, and that asking for time is not weakness. It's strategy.",
      "The kids will copy what you model. Give them something worth copying.",
    ],
  },
  {
    slug: 'what-i-learned-from-my-worst-parent-teacher-conference',
    title: 'What I learned from my worst parent-teacher conference',
    date: '2026-02-02',
    type: 'note',
    topic: 'reflection',
    tag: 'Saturday note · 5 min read',
    readTime: '5 min read',
    excerpt: "I've been on both sides of that table. The parent side is harder.",
    dek: null,
    img: null,
    featured: false,
    related: ['inspect-dont-expect', 'three-to-one-explained'],
    body: [
      "I have sat at the teacher's side of a parent-teacher conference table approximately four hundred times. I have sat at the parent's side exactly three times. **The parent side is harder.**",
      "My worst one was last spring. Henry's teacher — good teacher, kind teacher — told me he wasn't completing assignments. She was right. I knew she was right. I'd seen the missing homework. I'd asked about it. I'd done the wrong version of inspection — I'd noticed the problem but hadn't actually looked at what was creating it.",
      "The thing she said that stayed with me: *He's capable. He just seems to think that if he waits long enough, the assignment will go away.* That was not a description of Henry. That was a description of what I had accidentally taught him by not following through.",
      "The conference was uncomfortable. It was also exactly what I needed. I went home and changed the routine — we now sit together for twenty minutes after dinner, no exceptions, and I actually look at what he's working on. Not over his shoulder, with him. That's inspect, not surveil.",
      "If your kid's teacher is telling you something hard this year, I'd say: believe them. They are watching your kid in a room you never see. They are telling you something useful.",
    ],
  },
  {
    slug: 'on-crying',
    title: 'On crying — mine, theirs, the difference',
    date: '2026-04-13',
    type: 'note',
    topic: 'resilience',
    tag: 'Saturday note · 3 min read',
    readTime: '3 min read',
    excerpt: "I used to fix tears. Now I sit with them.",
    dek: null,
    img: null,
    featured: false,
    related: ['bad-moment-great-opportunity'],
    body: [
      "I used to fix tears. The moment one of my sons started crying I would move toward a solution — *here's what we can do, here's why it's okay, it'll be better by morning.* I was good at this. I was also, I eventually realized, not helping.",
      "What crying usually needs isn't a solution. It needs to be witnessed. **Sit with it. Say: I see that you're really upset. I'm here.** That's the whole thing. No fixing, no explaining, no *but on the bright side.*",
      "My own crying is a different story. I don't cry easily, and when I do I tend to do it in the car, alone, with the music up. My kids have seen me cry exactly twice — once at my father's funeral, once at the end of a difficult year when Theo said something unexpectedly kind and I wasn't prepared for it.",
      "Both times I let them see it. Both times I said, afterward: *I was feeling a lot of things right then.* I don't think it scared them. I think it taught them that feeling a lot is allowed, and that feelings pass.",
    ],
  },
  {
    slug: 'three-things-before-walking-through-the-door',
    title: 'Three things I do before walking through the door',
    date: '2025-12-07',
    type: 'note',
    topic: 'resilience',
    tag: 'Saturday note · 2 min read',
    readTime: '2 min read',
    excerpt: "The transition from work-brain to home-brain is the most important 90 seconds of my day.",
    dek: null,
    img: null,
    featured: false,
    related: ['be-the-weather'],
    body: [
      "The transition from work-brain to home-brain is the most important 90 seconds of my day. I used to skip it. I would walk in mid-thought, mid-stress, mid-problem, and immediately become the weather I didn't want to bring.",
      "**Now I do three things in the car before I get out:**",
      "One: I put the phone face-down and sit with whatever I'm feeling. Not to fix it. Just to know it's there. Unacknowledged feelings have a way of walking in the door ahead of you.",
      "Two: I name one thing I'm looking forward to inside. It sounds corny. It works. It sets the room I'm walking toward rather than the room I'm leaving.",
      "Three: Three breaths. Not a meditation. Just three actual deep breaths, which physiologically slow the heart rate and tell the nervous system that the emergency is over.",
      "The whole thing takes 90 seconds. On the other side of the door, three people are waiting to experience whatever I bring in. The 90 seconds is for them.",
    ],
  },
  {
    slug: 'on-letting-them-fail',
    title: 'On letting them fail — a small, weekly dose',
    date: '2025-05-04',
    type: 'note',
    topic: 'autonomy',
    tag: 'Saturday note · 3 min read',
    readTime: '3 min read',
    excerpt: "The goal isn't to protect them from failure. It's to make sure the failures are small enough to learn from.",
    dek: null,
    img: null,
    featured: false,
    related: ['i-do-we-do-you-do', 'inspect-dont-expect'],
    body: [
      "There's a version of parenting where the goal is to prevent failure. No missed homework, no bad grades, no social disasters, no hard consequences. I understand the impulse. Watching your kid fail is genuinely painful.",
      "But the goal isn't to prevent failure. **The goal is to make sure the failures are small enough to be instructive, and close enough together that they build a pattern instead of just a scar.**",
      "I let Sam (10) forget his water bottle for three weeks in a row this fall. He was thirsty every day. He started remembering his water bottle. That's a small failure teaching a small skill. That's the whole design.",
      "The version of this I'm still working on: letting them fail at the things that feel higher-stakes. The social thing that went sideways. The tryout they didn't make. The test they didn't study for. I know the right move is to let the consequence land and then help them process it. I know this. And yet every time, there's a part of me that wants to soften it.",
      "Working on it. Every week, a little more.",
    ],
  },
];
